name: Python package
on: 
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        echo `pwd`
        echo `ls -lrt`
        cd requirements       
        echo "current directory"
        pwd
        ls -lrt
        pip install -r requirements.txt
        echo "installing test requirements"
        pip install -r test_requirements.txt
    - name: train_pipeline
      run: |
        python bikeshare_model/train_pipeline.py
    - name: test_with_pytest
      run: |
        pytest 
    - name: package_building
      run: |
        python -m pip install --upgrade build
        python -m build
    - name: api_dockerizing
      run: |
        echo "dockerizing..."
        echo "current dir1"
        pwd
        ls -lrt        
        mv ./dist/*.whl ./bikeshare_model_api/
        pwd
        echo "current dir2"
        cd bikeshare_model_api
        echo "current dir3"
        pwd
        ls -lrt
        docker build -t bike_share_app .
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: guru2611/bike_share_api:latest, guru2611/bike_share_api:${{ github.run_number }}
